module.exports = (ids) => [
  {
    id: ids.applications[0],
    workflow_state_id: ids.states[0],
    user_id: 2,
    data: '{"sections": {"key": "value"}}',
    created_at: new Date(),
  },
  {
    id: ids.applications[1],
    workflow_state_id: ids.states[1],
    user_id: 2,
    data: '{"sections": {"key": "value"}}',
    created_at: new Date(),
    submitted_at: new Date(Date.now() - 10000),
    completed: true,
    test: 1,
  },
  {
    id: ids.applications[2],
    workflow_state_id: ids.states[2],
    user_id: 2,
    data: '{"sections": {"key": "value"}}',
    created_at: new Date(),
    submitted_at: new Date(Date.now() - 20000),
    completed: true,
    test: 1,
  },
  {
    id: ids.applications[3],
    workflow_state_id: ids.states[2],
    user_id: 2,
    data: '{"sections": {"key": "value"}}',
    created_at: new Date(),
    test: 1,
  },
  {
    id: ids.applications[4],
    workflow_state_id: ids.states[2],
    workflow_id: ids.workflows[3],
    user_id: 2,
    data:
      '{"sections": {"first_section": {"name": "Test Name", "previous_loan": false, "applied_principal": 500}}}',
    created_at: new Date(),
    test: 1,
  },
  {
    id: ids.applications[5],
    workflow_state_id: ids.states[2],
    workflow_id: ids.workflows[3],
    user_id: 2,
    data:
      '{"sections": {"first_section": {"name": "Test Name", "previous_loan": false, "applied_principal": 500}}}',
    created_at: new Date(),
    completed: false,
    deleted_at: new Date(),
    test: 1,
  },
  {
    id: ids.applications[6],
    workflow_state_id: ids.states[4],
    workflow_id: ids.workflows[4],
    user_id: 2,
    data:
      '{"sections": {"first_section": {"name": "Test Name", "previous_loan": false, "applied_principal": 500}}}',
    created_at: new Date(),
    completed: false,
    test: 1,
  },
  {
    id: ids.applications[7],
    workflow_state_id: ids.states[1],
    user_id: 2,
    data: '{"sections": {"key": "value"}}',
    created_at: new Date(),
    deleted_at: new Date(),
    submitted_at: new Date(Date.now() - 25000),
    completed: true,
    test: 1,
  },
  {
    id: ids.applications[8],
    workflow_state_id: ids.states[1],
    user_id: 2,
    data: '{"sections": {"key": "value"}}',
    created_at: new Date(),
    deleted_at: new Date(),
    submitted_at: new Date(Date.now() - 30000),
    completed: true,
    test: 1,
  },
  {
    id: ids.applications[9],
    workflow_state_id: ids.states[4],
    workflow_id: ids.workflows[4],
    user_id: 2,
    data:
      '{"sections": {"first_section": {"name": "Test Name", "previous_loan": false, "applied_principal": 500}}}',
    created_at: new Date(),
    completed: false,
    deleted_at: new Date(),
    test: 1,
  },
  {
    id: ids.applications[10],
    workflow_state_id: ids.states[4],
    workflow_id: ids.workflows[4],
    user_id: 2,
    data:
      '{"sections": {"first_section": {"name": "Test Name", "previous_loan": false, "applied_principal": 500}}}',
    created_at: new Date(),
    completed: false,
    deleted_at: new Date(),
    test: 1,
  },
  {
    id: ids.applications[11],
    workflow_state_id: ids.states[2],
    user_id: 2,
    data:
      '{"sections": {"first_section": {"previous_loan": false, "applied_principal": 50000}}}',
    created_at: new Date(),
    test: 1,
  },
  {
    id: ids.applications[12],
    workflow_state_id: ids.states[1],
    user_id: 2,
    data: '{"sections": {"key": "value"}}',
    created_at: new Date(),
    submitted_at: new Date(Date.now() - 30000),
    completed: true,
    test: 1,
  },
];
