module.exports = [
  {
    name: 'Create new user',
    permission: 'CAN_ADD_USER',
    scope: 'application',
    category: 'user',
    role_id: 1,
  },
  {
    name: 'Create new user',
    permission: 'CAN_ADD_USER',
    scope: 'company',
    category: 'user',
    role_id: 2,
  },
  {
    name: 'Get company users',
    permission: 'CAN_GET_USERS',
    scope: 'company',
    category: 'user',
    role_id: 2,
  },
  {
    name: 'Create role',
    permission: 'CAN_CREATE_ROLE',
    scope: 'application',
    category: 'role',
    role_id: 1,
  },
  {
    name: 'Create role',
    permission: 'CAN_CREATE_ROLE',
    scope: 'company',
    category: 'role',
    role_id: 2,
  },
  {
    name: 'Add user to role',
    permission: 'CAN_ADD_USER_TO_ROLE',
    scope: 'application',
    category: 'role',
    role_id: 1,
  },
  {
    name: 'Add user to role',
    permission: 'CAN_ADD_USER_TO_ROLE',
    scope: 'company',
    category: 'role',
    role_id: 2,
  },
  {
    name: 'Get company users',
    permission: 'CAN_GET_USERS',
    scope: 'company',
    category: 'user',
    role_id: 1,
  },
  {
    name: 'Get company users',
    permission: 'CAN_GET_USERS',
    scope: 'company',
    category: 'user',
    role_id: 2,
  },
  {
    name: 'Update user',
    permission: 'CAN_UPDATE_USER',
    scope: 'application',
    category: 'user',
    role_id: 1,
  },
  {
    name: 'Update company user',
    permission: 'CAN_UPDATE_USER',
    scope: 'application',
    category: 'user',
    role_id: 1,
  },
  {
    name: 'Create an application',
    permission: 'CAN_CREATE_APPLICATION',
    scope: 'company',
    category: 'application',
    role_id: 2,
  },
  {
    name: 'Add application note',
    permission: 'CAN_ADD_APPLICATION_NOTE',
    scope: 'company',
    category: 'application',
    role_id: 2,
  },
  {
    name: 'Submit application',
    permission: 'CAN_SUBMIT_APPLICATION',
    scope: 'company',
    category: 'application',
    role_id: 2,
  },
  {
    name: 'Add an application decision',
    permission: 'CAN_ADD_APPLICATION_DECISION',
    scope: 'company',
    category: 'application',
    role_id: 2,
  },
  {
    name: 'Get applications',
    permission: 'CAN_GET_APPLICATIONS',
    scope: 'company',
    category: 'application',
    role_id: 2,
  },
  {
    name: 'Get reports',
    permission: 'CAN_GET_REPORTS',
    scope: 'company',
    category: 'reports',
    role_id: 2,
  },
];
