module.exports = (ids) => [
  {
    id: ids.states[0],
    workflow_id: ids.workflows[0],
    contract_id: null,
    configuration_id: ids.configurations[0],
    start_date: new Date(),
    end_date: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: ids.states[1],
    workflow_id: ids.workflows[1],
    contract_id: ids.contracts[1],
    configuration_id: ids.configurations[3],
    analysis_schema_id: ids.analysisSchemas[0],
    start_date: new Date(),
    end_date: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: ids.states[2],
    workflow_id: ids.workflows[2],
    contract_id: ids.contracts[0],
    configuration_id: ids.configurations[2],
    start_date: new Date(),
    end_date: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: ids.states[3],
    workflow_id: ids.workflows[3],
    contract_id: null,
    configuration_id: null,
    start_date: new Date(),
    end_date: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: ids.states[4],
    workflow_id: ids.workflows[4],
    contract_id: null,
    configuration_id: null,
    start_date: new Date(),
    end_date: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: ids.states[5],
    workflow_id: ids.workflows[5],
    configuration_id: ids.configurations[5],
    start_date: new Date(),
    end_date: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: ids.states[6],
    workflow_id: ids.workflows[6],
    configuration_id: ids.configurations[6],
    start_date: new Date(),
    end_date: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
